import type { Metadata } from "next";
import { Familjen_Grotesk } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import { getServerSession } from "next-auth";
import { Providers } from "./providers";

const FamiljenGrotesk = Familjen_Grotesk({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-famijen-grotesk",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: any;
}>) {
  return (
    <html lang="en">
      <body className={`${FamiljenGrotesk.variable} antialiased transition-all duration-300`}>
        <div className="max-w-[95vw] m-auto">
          <Providers session={session}>{children}</Providers>
        </div>
      </body>
    </html>
  );
}